### PR TITLE
Add Product as upper type bound for asSchema

### PR DESCRIPTION
**Pull request by manuzhang**

### CODE REVIEW

**Comment by MrPowers** [comment]
Related issue: https://github.com/MrPowers/spark-daria/issues/78

**Comment by MrPowers** [comment]
@manuzhang - this looks good.  I don't really know too much about Product, but can infer what this is trying to do from your issue.  Can you please write a test to demonstrate that this revised code is throwing a compile time error instead of a MatchError at runtime?  Thanks!

**Comment by manuzhang** [comment]
@MrPowers `Product` is the superclass of both `case class` and `Tuple`. Not sure there is a way to expect a failure at compile time.

**Comment by MrPowers** [comment]
@manuzhang - thanks.  If you and @snithish think this is good, then you're right that it should get merged.  Adding it now.

Going to open an issue about potentially collaborating to open a Spark pull request for this function.  This should probably be a core function offered by Spark.

**Comment by MrPowers** [comment]
@manuzhang - uTest has a `compileError` macro (https://github.com/lihaoyi/utest#compile-error) that "works similarly to intercept, except it does its checks (that a snippet of code fails) and errors (if it doesn't fail) at compile-time rather than run-time".  Is it possible that we can use `compileError` to make sure the code you've added is working as expected in the test suite?

**Comment by manuzhang** [comment]
@MrPowers Interesting. Let me try

**Comment by manuzhang** [comment]
@MrPowers Please check out https://github.com/MrPowers/spark-daria/pull/91

**Pull request merged**
