### PR TITLE
Support extractFromJson with json path expression

### PR DESCRIPTION
**Pull request by manuzhang**

### CODE REVIEW

**Comment by MrPowers** [comment]
@manuzhang - Thanks for submitting this.  I'm really bad at JavaScript / JSON stuff, so feel free to let me know if any of these thoughts I'm about to float are off base.

* Can we rename this from `getJsonObject` to `fetchValueFromJsonObject`?  `getJsonObject` makes me think that the method will be returning a JSON Object.
* Can we rename the `path` parameter to be `key` or `jsonKey`?  

On another note, would you like to collaborate on a blog post on Working with JSON and Spark?  It seems like this is an important blog post for the community and you have a lot of good knowledge stored in your brain.

Is [any of this](https://stackoverflow.com/questions/49849374/spark-dataframe-with-json-as-string-in-it-to-be-cast-as-nested-json) relevant?

**Comment by manuzhang** [comment]
@MrPowers This transformation is similar to the existing `extractFromJson` method but instead of defining a tedious partial schema we can simply pass in a json path like `$.user.name` to extract the value (You may check out the [doc](https://github.com/apache/spark/blob/v2.4.3/sql/core/src/main/scala/org/apache/spark/sql/functions.scala#L3422) of the underlying `get_json_object` method). How about overloading `extractFromJson` as `fetchXXX` sounds like a remote action ?

I'd love to help as much as I can for the post.

**Comment by MrPowers** [comment]
@manuzhang - Overloading `extractFromJson` sounds like the best idea, great suggestion!  Can you please make that change and let me know when this is ready to be merged?  Thanks!

**Comment by manuzhang** [comment]
@MrPowers done!

**Comment by MrPowers** [comment]
Thanks @manuzhang!  BTW, feel free to make PRs directly off the main project going forward now that you're a project collaborator.  You can also work off your fork - whatever works best for you.

**Comment by manuzhang** [comment]
@MrPowers Thanks, I prefer the fork model to keep the main repo clean

**Pull request merged**
