### PR TITLE
Use pipe for accessing sql functions in sequential manner.

### PR DESCRIPTION
**Pull request by gorros**
#50

### CODE REVIEW

**Comment by MrPowers** [comment]
@gorros - sorry for the delayed response.  Will this work for the Column methods that take arguments (like `substr`)?

Thanks for the PR.  Looks like this could be promising!

**Comment by gorros** [comment]
@MrPowers I think this will not solve the issue with methods that take arguments since we will need to have methods with the corresponding signature like `(Column, String, String) => Column` and so on. But I will think about that.

**Comment by MrPowers** [comment]
@gorros - sorry for being so slow in responding.  I think this pipe method is pretty much the same as the `chain()` method that already exists: https://github.com/MrPowers/spark-daria/blob/master/src/main/scala/com/github/mrpowers/spark/daria/sql/ColumnExt.scala#L19-L48  Thoughts?

**Comment by gorros** [comment]
@MrPowers you are right.

**Comment by MrPowers** [comment]
@gorros - Great minds think alike!  I'm going to plan on building out the rest of the methods in the `FunctionsAsColumnExt` object.  It's pretty ugly, but I like the code that it let's me write.  Maybe I'll change my mind and delete it at some point in the future.  Thanks for the help as always!

**Pull request closed without merging**
