### PR TITLE
Add an array_sum function to sum all the numbers in an array

### PR DESCRIPTION
**Pull request by MrPowers**

### CODE REVIEW

**Comment by manuzhang** [comment]
@MrPowers From [the JIRA](https://issues.apache.org/jira/browse/SPARK-23911), it seems the higher order functions are only available in SQL

**Comment by nvander1** [comment]
If you want scala syntax support for the higher order functions: transform, exists, aggregate, etc. We could merge this into daria as it doesn't seem to be gaining traction on the main spark tree: https://github.com/apache/spark/pull/24232 @manuzhang  @MrPowers This will be more performant than a UDF or UDAF

**Comment by manuzhang** [comment]
@nvander1 does it work for older versions of Spark ?

**Comment by nvander1** [comment]
@manuzhang It will only work for spark 2.4 onward.

**Comment by nvander1** [comment]
Although I did some experiements today with custom native spark functions, so I think we could do the same to backport the higher order functions.

**Comment by manuzhang** [comment]
Sounds great ! Do you have examples I could try ?

**Comment by nvander1** [comment]
@manuzhang I'll work up an example this week for you to test out and link it here! Kind of a busy week, but if I don't have an update by sunday evening, ping me!

**Comment by MrPowers** [comment]
We can continue this conversation on the higher order functions issue: https://github.com/MrPowers/spark-daria/issues/85

Closing this one cause it's not needed anymore.

**Pull request closed without merging**
