### PR TITLE
Add schemaFor method to get StructType from Scala Type

### PR DESCRIPTION
**Pull request by manuzhang**

### CODE REVIEW

**Comment by MrPowers** [comment]
@gorros - Can you take a look and let me know your thoughts if you have a sec?

**Comment by gorros** [comment]
@MrPowers Looks good to me :)

**Comment by MrPowers** [comment]
Thanks for reviewing @gorros .  Thanks for the contribution @manuzhang!

**Comment by MrPowers** [comment]
@manuzhang - I just released spark-daria v0.31.0 with the new functions you added.  Thanks for the high quality contributions.  Feel free to submit a pull request anytime and I'll make sure to get it merged in 🤓

**Comment by manuzhang** [comment]
@MrPowers thanks for you great library. I implemented some of the functions for our prod cases myself while I should've just used your library !

**Pull request merged**
