### PR TITLE
Add a <==> operator that returns false if both columns are null

### PR DESCRIPTION
**Pull request by MrPowers**

### CODE REVIEW

**Comment by MrPowers** [comment]
@nvander1 @manuzhang - Can you please review this PR and let me know what you think?

I am kind of surprise that `null <=> null` in Spark and `null == null` in Scala both return true.  I guess we shouldn't dive down the null theory rabbit hole.

I need this behavior for some work I'm doing.  Do you think that `<==>` is a good method name?

**Comment by nvander1** [comment]
I would hesitate to add a new symbol and prefer a function like allNull
that could take an arbitrary amount of columns.  Also <=> is meant to
return true when both are null.

Le sam. 1 juin 2019 à 14:59, Matthew Powers <notifications@github.com> a
écrit :

**Comment by MrPowers** [comment]
@nvander1 - I agree that `<=>` is meant to return true when both columns are null, but [most SQL implementations return false when both columns are null](https://stackoverflow.com/questions/1843451/why-does-null-null-evaluate-to-false-in-sql-server) right?

`<=>` is consistent with Java / Scala (returning true when both columns are null), but not consistent with the "standard" SQL.  

I'd argue that the most theoretically correct return value for null safe equality comparison when both columns are null is null.

I'm actually glad we're having this conversation because I think it's important for us to set some clear guidelines for the community.  Might be best to overload the `<=>` operator with a flag that lets the user specify if `null <=> null` should return true, false, or null.

**Comment by nvander1** [comment]
Doesn’t the === operator return false if both are null in spark? I’m not
anywhere near a computer right now so I can’t verify

Le sam. 1 juin 2019 à 15:55, Matthew Powers <notifications@github.com> a
écrit :

**Comment by manuzhang** [comment]
@MrPowers @nvander1 Sorry for late response. I'm just back from vacation and will go through all the updates today.

**Comment by MrPowers** [comment]
@manuzhang - welcome back :)

@nvander1 - You cool with naming this function `eqNullSafeStrict`?  This should cover all the use cases:

```scala
null === null // null
null <=> null // true
null eqNullSafeStrict null // false
```

Let me know what you think!

**Pull request closed without merging**
