### PR TITLE
Excel epoch converter col functions

### PR DESCRIPTION
**Pull request by cmftall**
Add 3 Excel epoch converter col functions to be able to convert an Excel time epoch 1900-01-01:

- to unix timestamp
- to timestamp
- to date

under the assumption that there are 19 (not 17) leap years between 1900-01-01 and 1970-01-01, as in Excel.
I think we could generalize this functions for non Excel like datetime. 
One way to do that is to add a boolean arg to the function `excelEpochToUnixTimestamp` which is set to true if it is excel like date time col and false if not and readapt the `nbOfDaysBetween` :
`nbOfDaysBetween = 25569 if excel like and 25567 else`. Let me know what do you think.

PS: I am learning and enjoying your 2 books and your blog, by the way. I am looking forward for the Python version of your books ;)
Thanks for all this great work.

### CODE REVIEW

**Comment by MrPowers** [comment]
@cmftall - this looks great to me.  Thanks for the PR.

@gorros - can you please take a look and let me know what you think?  Thanks!

**Comment by gorros** [comment]
Looks good to me.

**Comment by cmftall** [comment]
@gorros thanks for the review

You're welcome @MrPowers.
Should I add epoch1900To__ functions to handle not excel-like datetime. I mean using the correct leap years detection algorithm, https://en.wikipedia.org/wiki/Leap_year ?

**Comment by MrPowers** [comment]
@cmftall - thanks for this contribution.  This is great work!

@gorros - thanks for reviewing.  Always feel confident merging after you take a look!

@nightscape - FYI, this code might also be helpful for the [spark-excel](https://github.com/crealytics/spark-excel) library 😄  Not sure, but let us know if contributing any of these functions to spark-excel would help!

**Comment by nightscape** [comment]
Hey @MrPowers, thanks for letting me know!
In spark-excel [we use a utility function](https://github.com/crealytics/spark-excel/blob/master/src/main/scala/com/crealytics/spark/excel/DataColumn.scala#L75) to convert from Excel's internal representation to normal timestamps and the user can then decide how to proceed with that timestamp (e.g. convert it to a date).
But should a use-case for those functions come up (I hope) I'll remember this PR :wink:

**Pull request merged**
